//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public string CaseID { get; set; }
        public string AttorneySerialNum { get; set; }
        public string ClientSerialNum { get; set; }
        public string ApplicationNum { get; set; }
        public string EntrustDate { get; set; }
        public string SalesmanName { get; set; }
        public string ClientName { get; set; }
        public string TechdocumentName { get; set; }
        public string CasedocumentName { get; set; }
        public string ExtraInfo { get; set; }
        public string ApplicationType { get; set; }
        public string ApplicationStatus { get; set; }
        public string ApplicationDate { get; set; }
        public Nullable<long> SuitFlag { get; set; }
    }
}
