//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string ProfessionDate { get; set; }
        public string 电话 { get; set; }
        public string 邮箱 { get; set; }
        public string 分公司 { get; set; }
        public string 部门 { get; set; }
        public string 组别 { get; set; }
        public Nullable<long> 在职状态 { get; set; }
        public string 入职时间 { get; set; }
        public string 职业经历 { get; set; }
    }
}
