//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskAttribute { get; set; }
        public string TaskCatogry { get; set; }
        public string Attorney { get; set; }
        public string DistributeDate { get; set; }
        public string FirstVirsionDeadlineInternal { get; set; }
        public string FirstVirsionDeadlineOutside { get; set; }
        public string FirstVirsionDate { get; set; }
        public string DoneDeadlineInternal { get; set; }
        public string DoneDeadlineOutside { get; set; }
        public string OfficalDeadline { get; set; }
        public string DoneDate { get; set; }
        public string ProcessStage { get; set; }
        public string TaskStatus { get; set; }
        public string CaseID { get; set; }
    }
}
